name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail_fast: false
      matrix:
        go: ['1.11', '1.12', '1.13', '1.14', '1.15']
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      
      - name: Check out source code
        uses: actions/checkout@v1
      
      - name: Run the test suite
        run: go test -v
